### ISSUE TITLE
Cannot connect to server

### ISSUE THREAD

**Issue by nadirlc** [RocketChat/Rocket.Chat.iOS#106]
Hello,

We are not able to connect to our Rocket Chat server from iphone. We have 2 installations of Rocket Chat. Both use sub folder urls. The urls are: https://exergoit.se/chat and http://valuehub.com/chat. We get this error: "Failed to connect to server".

Thanks,
Nadir Latif

**Comment by rafaelks** [comment]
@nadirlc Can you urls on this format? `wss://exergoit.se/chat/websocket` and `wss://valuehub.com/chat/websocket`?

**Comment by nadirlc** [comment]
Can you please rephrase your question. I am running the Rocket Chat installation behind Apache. Should I add the two urls to the apache virtual host configuration ?.

**Comment by rafaelks** [comment]
@nadirlc This URL's should be there already AFAIK. What's the URL you're using to connect with Meteor? That's the URL you should use for now in the app.

**Comment by nadirlc** [comment]
You mean the site url ? . It is set to https://exergoit.se/ for the first installation. For the second installation it is set to http://valuehub.com/

**Comment by rafaelks** [comment]
@nadirlc Haha, sorry about the confusion. Here's the explanation: the currently iOS app (`develop` branch) ask you for the web socket URL instead of the URL you type in your browser to connect to it. In the future you'll type `https://exergoit.se/chat/` and the app will figure out how to connect in your socket, but today, in the server URL you'll need to give the app the full web socket URL. So, you in your case:

- If you wanna connect to `https://exergoit.se/chat`, you will type `wss://exergoit.se/chat/websocket` in the server URL.
- If you wanna connect to `http://valuehub.com/chat`, you will type `wss://valuehub.com/chat/websocket` in the server URL.

I already created an issue to convert the URL automatically here #107.

Got it?

**Comment by nadirlc** [comment]
We entered wss://exergoit.se/chat/websocket but it redirects to https://exergoit.se/chat/websocket. Same with wss://valuehub.com/chat/websocket. It redirects to http://valuehub.com/chat

Ill try removing the sub folder from the url, so the url becomes http://chat.exergoit.se

**Comment by nadirlc** [comment]
When we changed the url to http://chat.exergoit.se it worked. We can access the chat from iphone now.

**Comment by rafaelks** [comment]
@nadirlc Oh, you were trying to use the Cordova app, not the native one. Anyway, will close the issue since you figured it out.

**Comment by CharlesOy** [comment]
@rafaelks Is the native app on App Store?

**Comment by rafaelks** [comment]
@CharlesOy Not yet.
