### ISSUE TITLE
Cant connect to my server with http (not use https)

### ISSUE THREAD

**Issue by dije** [RocketChat/Rocket.Chat.iOS#1155]
Hey Everyone, i want connect to my server http://103.**.**.154:8082 without ssl(https)  but only stuck in connection loading animation, so i change code in ConnectServerViewController.swift :

 var url: URL? {
        guard var urlText = textFieldServerURL.text else { return nil }
        if urlText.isEmpty {
            urlText = defaultURL
        }
        
       //return  URL(string: urlText, scheme: "https")<--Original Code from github
       //with this:
       return  URL(string: urlText, scheme: "http") 
    }

and try to connect again, but failed and show popup with message "Could not connect to this server!" with error log:

[WebSocket] wss://103.**.**.154:8082/websocket
 - did disconnect with error (Optional(Error Domain=NSOSStatusErrorDomain Code=-9847 "(null)" UserInfo={_kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9847}))

anyway my info.plist for NSApplicationSecurityTransport has been set:
 <key>NSAppTransportSecurity</key>
    <dict>
        
        <key>NSAllowsArbitraryLoads</key>
        <true/>
        
    </dict>

Anybody help me for this problem? thanks

**Comment by rafaelks** [comment]
@dije In order to connect to your server without SSL, you also need to change the WebSocket protocol to not be secure (`wss` will become `ws`):

https://github.com/RocketChat/Rocket.Chat.iOS/blob/4406fdc9f952fcc8707cbd850fa9db45a5414541/Rocket.Chat/Extensions/URLExtension.swift#L68-L82

**We don't recommend using the app without SSL**.
