### ISSUE TITLE
[BUG] App hangs from time to time

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat.iOS#1177]
I'm facing hanging of the UI sometimes - in most cases I want to scroll but can't. Rest of the UI is unresponsive too, but Instabug works (can move the Bubble around).
I'll try to reproduce the error with flex opened.

**Comment by cardoso** [comment]
We have a big hang related to our function "imageWithTint" function in UIImageExtension.swift

The calls to CGContext.draw are causing a big pause in the main thread. 

We need to find another way to do what we're currently doing with the method. (Coloring standard avatars and some icons).

**Comment by Sameesunkaria** [comment]
## Instruments

I am facing a similar issue. Sometimes the apps hangs for short durations usually when i'm scrolling up. There is also a prolonged hand (about 1-3 seconds) when the app starts up and begins loading the chat from the server.

So I have been digging around Instruments and found that the execution on main thread stops for a while when its saving chat to the realm database. (Read thread in the screenshot)

There are **over** 64 threads waiting to write to the database, and since realm does not perform concurrent writes, all the threads are essentially working in a queue (the small spikes seen in the screenshot for all threads except the red and the blue one). The spikes represent the `Realm.write(_:)` operation.

![rcmainwait](https://user-images.githubusercontent.com/7317008/37022372-d3290c58-2148-11e8-9e8c-8712f62962da.png)

I believe the blue thread is helping realm maintain it's MVCC. 

## Xcode

In Xcode if i pause the execution that that instant, the main thread is on `_ulock_wait` . 

![rcmainwait](https://user-images.githubusercontent.com/7317008/37023123-f53095bc-214a-11e8-97f3-2debd8efc5d9.png)

What I can conclude from this deep dive is that, the main thread is waiting since there are too many concurrent threads waiting on completion of execution, and GCD only supports a max of 64 threads.
(Not sure on the thread limit, but I found a stackoverflow: https://stackoverflow.com/questions/15150308/workaround-on-the-threads-limit-in-grand-central-dispatch)

One possible fix for this, is to not spawn a new queue for every write operation, rather use one queue that does all the writing. 

I am not sure how much of this is correct, but that's why I'm posting this; to get any feedback on this theory.

**Comment by rafaelks** [comment]
@Sameesunkaria Thank you very much for looking into it! I think you're totally right and all the Realm things we're doing are destroying our main thread. We're doing lots of things on Realm because our WebSocket connection sends one message per time and we process it one message per time right now.

Do you have any solution in mind (or in code :-)) already? Let's try using one queue to all the writing and see what happens. All writings are happening in `RealmExtensions.swift` file.

**Comment by Sameesunkaria** [comment]
I did manage to fix the Realm issue by creating a separate queue for all the Realm write events. But thats wasn't all. Now that realm was not holding back the main queue, I saw a lot of JSON parsing happening on the main thread, which also brought the app to a halt. I was not able to find out where the json was being parsed, and that was yesterday. I haven't looked into it since, because I am working on getting the local (in app) notifications to work.

**Comment by rafaelks** [comment]
@Sameesunkaria Oh... the JSON parsing happens in a few places where we map the response after getting the results from the WebSocket. You can look into this method in `SocketManager.swift`:

```swift
func websocketDidReceiveMessage(socket: WebSocket, text: String, response: WebSocket.WSResponse) {
   ...
}
```

Thank you!

**Comment by Sameesunkaria** [comment]
Also I saw some performance issues with emojis. Not exactly sure what the issue might be, but it is something you can experience on a real device as well. Try scrolling up on a chat, and every time the animation stutters (when its not loading the older chats) you will see a cell with emojis come on screen.

**Comment by rafaelks** [comment]
@Sameesunkaria Yes... I think the main reason is that we've a super big emoji file and we probably try to find it every time we replace it on the text. We could also have some improvements on this algorithms.

**Comment by Sameesunkaria** [comment]
@rafaelks Is there a reason as to why `static func updatePublicSettings(_ auth: Auth?, completion: @escaping MessageCompletionObject<AuthSettings>)` in `AuthSettingsManager` has a call to `Realm.executeOnMainThread`? Can this closure be called on a background thread?

**Comment by rafaelks** [comment]
@Sameesunkaria I don't think there is... it doesn't need to be on main thread AFAIK, but we need to call the completion block on main thread, in order to update the interface.
