### ISSUE TITLE
[BUG] Edit Profile stuck when saving without changes

### ISSUE THREAD

**Issue by cardoso** [RocketChat/Rocket.Chat.iOS#1524]
Edit Profile screen keeps loading after pressing save without changing anything.

Also, textfields are kept interactive and you can still go to "change your password" screen 🤔

**Comment by filipealva** [comment]
@cardoso the endless loading is fixed on #1526, but the fact that the textfields kept interactive and you still go to "change your password" is intentional.

The fields will be interactive always when the screen is in editing profile state. I did some research on it, and the apps that work with "editing/viewing" on the same screen instead of using a screen to view and another to edit the data usually allow the user to go keep in the navigation stack even when in `editing` state. 

WhatsApp is a good example, if you go to the `Settings` tab, tap on the profile row then start editing your name you will see that the screen enters in `editing` state, similar to what we did with the back button changing to `cancel` and adding an `OK` to save on the right bar button item, and you can still navigate to update your `status` (almost the same navigation hierarchy that we have with "change your password") . 

I know it can be confusing, but we actually tried some different flows for this editing/viewing profile screen and we ended up with this one because it was the better fit, I personally think that when mixing these two contexts in a single screen will always wind up more confused than separating them into different contexts and exploring the contexts better, this is why a lot of apps are using a screen to view and another to edit profiles. A good example of this behavior is the Contacts app on iOS, the viewing screen for a contact is hugely different of the editing screen because even though the content is the same the context of each screen is totally different.

Sorry about the TL;DR, it's a topic I like to discuss 🤓

**Comment by cardoso** [comment]
Ok @filipealva . Makes sense 🙂
