### ISSUE TITLE
[BUG] Replies via notifications doesn't work

### ISSUE THREAD

**Issue by Zegorax** [RocketChat/Rocket.Chat.iOS#1536]
- Your Rocket.Chat app version: 2.1.1
- Your Rocket.Chat server version: 0.63.1
- Device (or Simulator) you're running with: iPhone 7+

When receiving a notification and replying by "dragging" it towards the bottom, the message doesn't get send. 
After opening the app, the message is not there either.

**Comment by cardoso** [comment]
Hi @Zegorax . Sorry for that. This is fixed in version 2.2.0 (PR: #1531). It's already available for testing in our TestFlight and the App Store version should be upgraded soon.

If you want to take part in our TestFlight, send me your Apple ID via DM at https://open.rocket.chat/ @matheus.cardoso

Thanks for your patience! 🙂
