### ISSUE TITLE
[QUESTION] Force status changes

### ISSUE THREAD

**Issue by bluerockny** [RocketChat/Rocket.Chat.iOS#1660]
When I use the iOS app and switch to another app, my status is automatically set to "away" and when i sleep the phone it's set to "offline" (invisible?). I would like to be able to force my status to online (or away) at all times, even if the phone is asleep. Since push notifications are working well for me, I'm basically always "online" if I have my phone / watch on me. We host our own Ubuntu snap installation, currently 0.63.3.

**Comment by rafaelks** [comment]
@bluerockny You want your user to always stay online, even if you're not online?

**Comment by bluerockny** [comment]
If push notifications are working properly (and they are) I'm effectively always online with my iphone and watch as long as they're with me. I don't want other users to think I won't read their messages if they see me as "offline" (they might be reluctant to send them to begin with in that case). That's why I would like to be able to force my status (even if it says "iphone" or something similar)

**Comment by rafaelks** [comment]
@bluerockny Currently there's no way you can set your status to "force" online. Please, go to our forums and create a new feature request about your need, so we keep the discussion over there: https://forums.rocket.chat.

Keep in mind that online on the mobile is suppose to be only when you're actually online, with the application opened. Otherwise the status doesn't make any sense IMHO.

**Comment by ceefour** [comment]
@rafaelks I'd say a more accurate status for "app not opened, but able to receive notifications" is "away".

Currently, `offline` does not distinguish between:

1. app not opened, but able to receive mobile push notifications
2. app not installed / user not logged in / user gone / user not contactable 

Two very different states in practice, but currently same status and very confusing.

I agree with @bluerockny in that case status should not be `offline`, IMHO it should be `away`.

**Comment by plmorpheus** [comment]
> @rafaelks I'd say a more accurate status for "app not opened, but able to receive notifications" is "away".
> 
> Currently, `offline` does not distinguish between:
> 
> 1. app not opened, but able to receive mobile push notifications
> 2. app not installed / user not logged in / user gone / user not contactable
> 
> Two very different states in practice, but currently same status and very confusing.
> 
> I agree with @bluerockny in that case status should not be `offline`, IMHO it should be `away`.

I totally agree. The status should be "away" if user has installed app which works in background and is able to receive push. Technically, if user is able to receive push notification, he is online because notification with message reach him. However, because the user does not necessarily read this message immediately, the best solution is the "away" status so that the sender knows that the message will reach the recipient device but this one does not necessarily read it immediately. The offline status suggests that the message will not even reach any of user's device, which is not true.

**Comment by diegolmello** [comment]
This repo is deprecated: https://github.com/RocketChat/Rocket.Chat.iOS#important---please-read-this-first
