### ISSUE TITLE
[BUG] Unable to login 

### ISSUE THREAD

**Issue by mattpacura** [RocketChat/Rocket.Chat.iOS#1738]
**Details:** Unable to login. Currently getting an error message when trying to login to my server using valid credentials. It worked when I first upgraded from 2.4.0 > 2.4.1 but after logging out, I'm unable to log back in. I've confirmed on another device that 2.4.1 does not work with my current server on a clean install.

- Rocket.Chat app version: 2.4.1
- Rocket.Chat server version: 0.59.3
- Device (or Simulator) you're running with: iPhone 6S, iOS 11.2.6

**Error:** 

> Oops! Something wrong happened while trying to login.

**Comment by mattpacura** [comment]
@rafaelks - the app version is "2.4.1" which is the latest on the App store. Do you mean server version? If so, it's barely over 6 months old, seems like a new version of the app shouldn't break that?

**Comment by rafaelks** [comment]
@mattpacura I mean the server version. I agree with you that 6 months old should not break, but since we're moving real fast on the development side and we're not even in version 1.0.0 yet, we're making sure to support maximum of 3 versions before (3 months) the latest one. This version of the server you're running doesn't have lots of APIs that we're using in the iOS and Android apps. 👍

**Comment by mattpacura** [comment]
@rafaelks - Understood, thanks. I'll close this out per your comments.

**Comment by harridu** [comment]
Maybe it would be possible to improve the error message? It should be easy to detect that client and server don't support a common API.
