### ISSUE TITLE
[BUG] IOS 11.4.1 Receiving notifications even if it's not logged

### ISSUE THREAD

**Issue by ggazzo** [RocketChat/Rocket.Chat.iOS#2115]
@cunhazord commented on [Tue Aug 07 2018](https://github.com/RocketChat/Rocket.Chat/issues/11701)

### Description: 
I'm getting notifications even if I'm not logged in any server

### Steps to reproduce:

1.  Open RocketChat app
2.  Log out from any server
3.  Close RocketChat
4.  Test it

### Expected behavior: 
Not get notifications

### Actual behavior: 
Receiving notifications from a chat I'm not logged

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.4
- Operating System: IOS 11.4.1

**Comment by rafaelks** [comment]
@cunhazord What's the server version you tried?

**Comment by cunhazord** [comment]
@rafaelks 0.66.3

**Comment by rafaelks** [comment]
@cunhazord This was probably some request failure on removing the token from your user on the logout process, I just tried here and is not reproducible. In order to fix that specific for your case, please uninstall the app and install again or remove the specific token from the database of your server.

I'll close the issue for now and we can reopen in the future if the issue appears again. 👍
