### ISSUE TITLE
[BUG] It is not possible to change server

### ISSUE THREAD

**Issue by slajerek** [RocketChat/Rocket.Chat.iOS#2122]
- Rocket.Chat app version: 3.0.4 (206)
- Rocket.Chat server version: 0.65.1
- Device: iPhone 6, iOS 10.3.3

How to switch servers? Previously that was in a sidebar menu on the left. After update I see new layout and in top bar underneath "Messages" text I see a cut name of the current server (with "..." in the middle of name) and down-arrow that looks like a pull-down menu. Unfortunately nothing happens when I tap the server name. Should it open a menu to select servers (just guessing)? Anyway - what's the correct way to select servers in this new layout?

By the way, IMHO previous layout was much, much better.

**Comment by filipealva** [comment]
Hi @slajerek, thanks for reporting! 

I was able to reproduce this issue, it's happening on iOS 10 only, I'm sorry that you could not fully experience our new layout due to this issue. We'll prioritize this fix since it critically impacts the app usage for iOS 10 users. 

Thanks for your general feedback on our new layout as well. If there are any specific feature or interaction you had on the previous layout that is missing on the new one, please let us know. The redesign was a strategic move. I'm sure that with the community feedback we will be able to build the best iOS client ever.
