### ISSUE TITLE
Support "Text Box" kind of message

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#265]

**Comment by Jellyfrog** [comment]
Is this the "attachment" message type?
Have some channels that basically only looks like this:
![img_1623](https://cloud.githubusercontent.com/assets/759887/22955953/51b903c4-f31f-11e6-8060-7ee3fac3278f.PNG)
Due to usage of https://rocket.chat/docs/developer-guides/rest-api/chat/postmessage#attachments-detail

**Comment by rafaelks** [comment]
Yes, exactly that. 👍
