### ISSUE TITLE
Unable to Upload Media to Thread

### ISSUE THREAD

**Issue by anthonylavado** [RocketChat/Rocket.Chat.iOS#2700]
- Your Rocket.Chat app version: 3.5.0 (257)
- Your Rocket.Chat server version: 1.0.3
- Device (or Simulator) you're running with:  iPhone X, iOS 12.3 (16F156) 

On iOS, you can try uploading media (picture, drawing, file) to a thread, but it does not display. It simply vanishes.

**Comment by rasos** [comment]
Uploading a photo to a private channel does not work either on RC server version 0.74.1.

**Comment by reetp** [comment]
Please follow this when reporting issues.

https://rocket.chat/docs/contributing/reporting-issues

Always test on the latest version of Rocket.Chat first. Development moves rapidly and your problem could be fixed already.

Also when commenting please make sure the issue is like for like. There are a lot of differences between v0.74.x and v1.0.x  - v0.74.x doesn't even have thread support.....

**Comment by anthonylavado** [comment]
@reetp - Apologies for not following the format myself, I was only going by the issue template that was provided.

I've tested this just now on the public server (open.rocket.chat), and the issue remains. If I upload from the web interface, it works and is visible on mobile. It's strictly uploading from the web interface that items just disappear/silently fail.

This is using the latest app store version, 3.5.0.
