### ISSUE TITLE
Add support for themes

### ISSUE THREAD

**Issue by marbetschar** [RocketChat/Rocket.Chat.iOS#496]
It would be awesome, to have the Rocket.Chat iOS app behave like its macOS counterpart in terms of colors and theming. That is, using the colors defined in the backend for the main menu and https://github.com/RocketChat/Rocket.Chat.iOS/issues/480 would be super cool too!

### Here is how it looks on the desktop app
![bildschirmfoto 2017-05-25 um 09 33 59](https://cloud.githubusercontent.com/assets/392542/26441048/46c3c8ce-412f-11e7-887e-975f36795f7e.png)

### And this is how it looks like on iOS
![img_2324](https://cloud.githubusercontent.com/assets/392542/26441070/5a031d86-412f-11e7-8a30-3abd96da3d6c.PNG)

**Comment by rafaelks** [comment]
@marbetschar You're right, it will be awesome when we support it. 😃 

This issue duplicates #273, so, I'm going to close it.

BUT, we're blocked right now to support it, because we're changing the name of the elements and creating some kind of components in our back-end. When this is ready in our back-end, we can support the colors and themes in our native apps. 👍
