### ISSUE TITLE
[NEW] Custom Field Support for Registration

### ISSUE THREAD

**Issue by nicdaddy** [RocketChat/Rocket.Chat.iOS#611]
Enable custom field support in the iOS registration process.

**Edit:**

In the administration interface (web), it's possible to specify custom fields for the registration process:

We need to display these custom fields when registering a new account

| Settings (Web) | Register Screen (Web)
| - | - |
| ![image1](https://i.imgur.com/FJcrgkB.png) | ![image1](https://i.imgur.com/6YZLg4j.png)

Where to look:

-- Support 'Accounts_CustomFields' setting
[AuthSettings.swift](https://github.com/RocketChat/Rocket.Chat.iOS/blob/master/Rocket.Chat/Models/AuthSettings.swift)
[AuthSettingsModelMapping.swift](https://github.com/RocketChat/Rocket.Chat.iOS/blob/master/Rocket.Chat/Models/Mapping/AuthSettingsModelMapping.swift)

-- Display custom fields
[Auth.storyboard](https://github.com/RocketChat/Rocket.Chat.iOS/blob/master/Rocket.Chat/Storyboards/Auth.storyboard)
[SignupViewController.swift](https://github.com/RocketChat/Rocket.Chat.iOS/blob/master/Rocket.Chat/Controllers/Auth/SignupViewController.swift)

How web does it:
[Rocket.Chat/customFieldsForm.html](https://github.com/RocketChat/Rocket.Chat/blob/master/packages/rocketchat-lib/client/views/customFieldsForm.html)

**Comment by vadimue** [comment]
Hi there. How I can get some test response with not empty Accounts_CustomFields parameter?

**Comment by rafaelks** [comment]
@vadimue Hey! We suggest you deploy a new server (you can see how to do it [here](https://github.com/RocketChat/Rocket.Chat#deployment)) or you can deploy a new server in our [SaaS](https://rocket.chat/hosting) service (for free now).

After you create your server, the first user registered will be the administrator. Then you can change the custom fields the way you want, testing many different variations.

**Comment by vadimue** [comment]
@rafaelks Hi again, I am working on this feature for two days and can`t understand several things. I started from creating models for custom fields and faced with a problem of inheritance of Realm Objects. I added customFields property to AuthSettings model and automatically have to do all staff with Realm Objects. Do we need save custom fields to the storage?

**Comment by rafaelks** [comment]
@vadimue Yes, the idea is to save the custom fields into store as well. We really have no way to create custom columns in Realm, but we can be creative in order to solve this problem. Here's one idea:

1) Create a "UserCustomFields" model in Realm;
2) This model will look like this:

```
UserCustomFields
- user: User
- key: String
- type: String (string | int | bool | float | date )
- valueString: String
- valueInt: Int
- valueBool: Bool
- valueFloat: Float
- valueDate: Date
```

3. Then you add a new property to the User model, called `customFields` that is a List of `UserCustomFields`.

You can take a look what kinds of fields Realm supports here: https://realm.io/docs/swift/latest/api/Classes/Object.html.

What do you think? :-)

**Comment by vadimue** [comment]
@rafaelks It is so good simple solution. But in sample JSON we see type `Select`, which instead of single value contains `options` field (array of values) and the default value (also strange field named `modifyRecordField`, which I ignored right now). And I expect creation of other different types like select, so I thought about inheritance like (`class BaseField` <- `class SelectField`, `class TextField` etc.) It is more complex use case. If it does not required, I will be very happy. Of course we can add another one field to your `UserCustomFields` like `options`, but in this case, we need another one field `default`. So `UserCustomFields` can swell very quickly and smells after this :) Please stop me in my wrong thought direction, if it so.

**Comment by vadimue** [comment]
Also I added `customField` to `AuthSettings`, not to `User`.

**Comment by rafaelks** [comment]
@vadimue Did some research, these are the kinds of fields we may have:

```
{
    "role": {
        "type": "select",
        "defaultValue": "student",
        "options": ["teacher", "student"],
        "required": true,
        "modifyRecordField": {
            "array": true,
            "field": "roles"
        }
    },
     "twitter": {
        "type": "text",
        "required": true,
        "minLength": 2,
        "maxLength": 10
    }
}
```

**Comment by vadimue** [comment]
#761
