### ISSUE TITLE
[BUG] List of subscription seems to not be following any specific order

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#846]
# Description

On my list, I've this order right now... let's change it to be alphabetically.

- a..
- a..
- l..
- s..
- b..

## Screenshot

![img_0122](https://user-images.githubusercontent.com/551004/32201435-3917e00a-bdbe-11e7-97c2-1aabc182fb93.png)

**Comment by filipealva** [comment]
I'm on it, almost done! I was thinking while implementing it: it's not tricky to manage (crud) the servers based on their indexes on the list stored on the user defaults instead of some unique id?

Initially I thought that the best way to do that was to only sort the list of servers at the moment of presenting it, but as we use the index in that list to manage the servers we will have to sort it everywhere (not only when we decide to show it, but even to "query" a server to remove or add a new one).

**Comment by filipealva** [comment]
It seems that it is already fixed 🤔  or something more than just having subscriptions is required to simulate this scenario?

<img width="252" alt="screen shot 2017-11-03 at 19 00 54" src="https://user-images.githubusercontent.com/6117280/32395698-64ece8f2-c0c9-11e7-9199-c40515232dd9.png">

**Comment by rafaelks** [comment]
@filipealva Still happens to me.

**Comment by filipealva** [comment]
@rafaelks just added more subscriptions and I was able to reproduce (and fix) it 👍
