### ISSUE TITLE
 RocketChat+ app crashes on iOS

### ISSUE THREAD

**Issue by gremwell** [RocketChat/Rocket.Chat.iOS#883]
- Your Rocket.Chat app version:   don't know - it crashes before I can check the version. It is the latest version available from Apple Appstore
- Your Rocket.Chat server version: 0.58.3
- Device (or Simulator) you're running with: iPhone iOS 10.3.3

RocketChat app crashes on iOS. This happens when I activate the app after a new message notification.

Steps to Reproduce:

-     Have RocketChat+ iOS app running in background
-     Have somebody message you through rocket chat with notifications enabled
-     Tap rocket chat app
-     App crashes during loading

**Comment by rafaelks** [comment]
@gremwell This is 99% for sure some issue with Markdown that we fixed in 1.7.0 (currently in `develop` branch). Do you have an email we can invite your to try our beta version of the app thought TestFlight? If yes, send me over `rafael.kellermann at rocket dot chat`, please. I'll close the issue for now, unless we found that this isn't fixed yet.

**Comment by gremwell** [comment]
@rafaelks - I've sent you an email.
