### ISSUE TITLE
[CHORE] Remove all new SwiftLint warnings from the code

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#908]

**Comment by Moeez007** [comment]
Hello,

Can you please tell me when this issue will be solved, as for now I am not able to build the app.

Thanks

**Comment by artrmz** [comment]
@Moeez007 you should be able to build the app regardless of this issue. Are you sure you have SwiftLint installed on your machine? It might be the reason you are not able to.

**Comment by Moeez007** [comment]
I have tried to install the swiftlint library in the project by including the pod 'SwiftLint' line in the pod file of the rocket chat app but still got the error, Am I doing something wrong here ?

**Comment by artrmz** [comment]
@Moeez007 Just install it manually on your machine or using home-brew (`brew install swiftlint`).

**Comment by Moeez007** [comment]
I just installed the swiftlink.pkg in my macbook pro, but still the same issue

**Comment by Moeez007** [comment]
I have downloaded the version 1.6.0 from the below link and just ran pod install and tried to build.

**Comment by rafaelks** [comment]
@Moeez007 SwitLint has only warnings right now, you should be able to compile the app with no problem. Are you sure you're following [our instructions](https://github.com/RocketChat/Rocket.Chat.iOS#setting-up-a-development-environment)?

**Comment by leonardo-ferreira07** [comment]
There is a lot of issues on SwiftLint? Because I figured out 3 related to the `class_delegate_protocol` rule, and also I fixed everyone related to the `characters.count` pointed by the compiler. There's more related to `characters` that I didn't fix yet.

Also I've checked the TODOs, it also can be considered for this issue? 

Thank you in advance, I would like to know more about this questions and what do you expect as resolution for this issue, and then send my pull request.

**Comment by cardoso** [comment]
You should leave the TODO warnings @leonardo-ferreira07, everything else can be fixed. Thanks!
