### ISSUE TITLE
[NEW] Let user update name, username, email, password and avatar

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.iOS#962]

**Comment by dennispost** [comment]
I will take of it

**Comment by rafaelks** [comment]
@dennispost Thank you, I'll assign the issue to you. Here are the REST API docs: https://rocket.chat/docs/developer-guides/rest-api/users/update.

**Comment by rafaelks** [comment]
@dennispost Hey Dennis, are you still working on this issue? Let me know if you need some help. Thanks!

**Comment by dennispost** [comment]
Yep, the current status can be found here: https://github.com/dennispost/Rocket.Chat.iOS/tree/feature/Add_Profil_and_Settings_ViewController

**Comment by rafaelks** [comment]
Great, thank you!!!

**Comment by cardoso** [comment]
Looking very very good, thank you!

**Comment by dennispost** [comment]
@rafaelks 
How do we can handle the verification of a changed email address? Currently I will receive a successful answer from the API but also the following Socket message: 
```json
{
  "fields" : {
    "emails" : [
      {
        "verified" : false,
        "address" : "mynewemail@somewhat.com"
      }
    ]
  },
  "collection" : "users",
  "id" : "myU5er1d",
  "msg" : "changed"
}
```

**Comment by dennispost** [comment]
@rafaelks 
In addition a password change request (sent to /api/v1/users.update), returns success but actually the password did not change.

**Comment by graywolf336** [comment]
@dennispost how are you changing the email address? Like what endpoint and what provided data?

Also, what data are you passing to request a password change?

**Comment by dennispost** [comment]
@graywolf336 I’m using the users.update endpoint

**Comment by dennispost** [comment]
@graywolf336 here are the data snippets for my update requests against _**api/v1/users.update**_:
All requests are authenticated requests with X-Auth-Token header present.

Data sent for password change:
```json
{
	"userId" : "tb65MjQvimH4iP95Y",
	"data" : {
		"password" : "myNewPassword1234!"
	}
}
```

Data sent for email change:
```json
{
	"userId" : "tb65MjQvimH4iP95Y",
	"data" : {
		"email" : "myNewEmail@somefancy.com"
	}
}
```

For both requests I get a user object as response with ` "success": true`
Password change does not work. E-Mail change does work without verification.

**Comment by rafaelks** [comment]
@graywolf336 @rodrigok Can we have any kind of help here? I think we have a bug in our API.

**Comment by dennispost** [comment]
😔 We could remove some settings from our scope and go only with the working ones.

**Comment by cardoso** [comment]
@dennispost, that's what I was discussing with @rafaelks. If we need to fix the API, it still wouldn't work on 80% of servers. We can look into supporting the other settings later.

**Comment by rafaelks** [comment]
@dennispost Could you open a PR with your changes so we could work on top of it? Thank you!!!

**Comment by dennispost** [comment]
@rafaelks I opened PR #1260, but I can't push my latest work until tomorrow.

**Comment by MarcosSpessatto** [comment]
@rafaelks @dennispost , in case of the `verified` property i opened [this](https://github.com/RocketChat/Rocket.Chat/pull/9719) PR, which i think corrects the problem. In case of the password not being updated, you may take a look if maybe the `“edit-other-user-password”` property is not set correctly in the admin panel, described it the docs https://rocket.chat/docs/developer-guides/rest-api/users/update/.

**Comment by filipealva** [comment]
@MarcosSpessatto 

1. Shouldn't the `edit-other-user-password` be related only to the cases where a user is trying to change another user's password? I mean, a regular user should be able to update its own password without depending on any admin panel settings, right? 

That's the issue we are going through, a user is trying to change its own password and even though the request results in success the password is not being updated at all.

2. About the `verified` property: what's the purpose of this property? Shouldn't the backend be responsible to send an e-mail to the new unverified user e-mail? If I force the `verified` property to be `true` while updating the e-mail through the mobile app I'll only cause this information to be inconsistent because the e-mail wasn't actually verified. 

So I think that we should not set `verified` as `true` while updating a user's e-mail from a mobile app. The only place that should set `verified` as `true` is a webpage that is triggered by an URL sent to the user's e-mail so we can actually verify if the e-mail is valid. 

I mean, if we are not using the `verified` property to make sure that an e-mail was verified by ourselves in the past I don't know why we need to have a `verified` property 🤔.

I'm just trying to understand, please let me know if I got something wrong about the `verified` property and if I should actually set it as `true` even without actually verifying it.

**Comment by dennispost** [comment]
@filipealva I totally agree
