### ISSUE TITLE
[BUG] Data getting mixed between servers

### ISSUE THREAD

**Issue by cardoso** [RocketChat/Rocket.Chat.iOS#976]
Channels and messages from open.rocket.chat appearing in my server cardoso.rocket.chat

![](https://i.imgur.com/4PhfevC.png?1)

This happens when changing servers.

**Comment by TheReal1604** [comment]
@cardoso I saw some similar issue in my webserver logs. The app was requesting user profile pictures from the old server on the new one (at switch)

This means: 

Connected to chatA on serverA
Switch to chatB on serverB
User profile picture userA on serverA is requested when switching to serverB from serverB.

This is bad, because this leaks usernames from serverA to serverB. (in the webserver access logs)

**Comment by cardoso** [comment]
That's weird @TheReal1604. Would you know anything about that @rafaelks?

Is it a REST call or WebSocket?
Does it happen frequently? If so, can you open an issue with the logs and steps to reproduce?

**Comment by rafaelks** [comment]
@TheReal1604 What version of the app are you talking about? I think I know what's happening... when we disconnect from the server and open the other chat controller (or auth controller) the first chat controller keeps opened for a while and refreshes the screen on socket connection status changes.

**Comment by TheReal1604** [comment]
@rafaelks I tested this again and this is NOT happening anymore. 

Thanks guys!
